apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: myapp
type: Opaque
stringData:
  POSTGRES_HOST: "database-1.cvkyc0o8621q.ap-south-1.rds.amazonaws.com"
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "Aniket.Mori1626"
  POSTGRES_PORT: "5432"
